/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface NeonDrawLotteryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "buyTicket"
      | "claimPrize"
      | "closeDraw"
      | "createDraw"
      | "draws"
      | "fulfillDraw"
      | "getDrawTicketIds"
      | "nextDrawId"
      | "nextTicketId"
      | "owner"
      | "pause"
      | "paused"
      | "pendingClaims"
      | "renounceOwnership"
      | "requestDrawRandomness"
      | "setVRFCoordinator"
      | "tickets"
      | "transferOwnership"
      | "unpause"
      | "vrfCoordinator"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DrawClosed"
      | "DrawCreated"
      | "DrawSettled"
      | "OwnershipTransferred"
      | "Paused"
      | "PrizeClaimed"
      | "TicketPurchased"
      | "Unpaused"
      | "VRFRequested"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "buyTicket",
    values: [BigNumberish, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "claimPrize",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "closeDraw",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createDraw",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(functionFragment: "draws", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "fulfillDraw",
    values: [BigNumberish, BigNumberish[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getDrawTicketIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextDrawId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextTicketId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingClaims",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestDrawRandomness",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setVRFCoordinator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "tickets",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "vrfCoordinator",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "buyTicket", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimPrize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "closeDraw", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "createDraw", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "draws", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fulfillDraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDrawTicketIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nextDrawId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nextTicketId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingClaims",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestDrawRandomness",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setVRFCoordinator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tickets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "vrfCoordinator",
    data: BytesLike
  ): Result;
}

export namespace DrawClosedEvent {
  export type InputTuple = [
    drawId: BigNumberish,
    ticketCount: BigNumberish,
    poolBalance: BigNumberish
  ];
  export type OutputTuple = [
    drawId: bigint,
    ticketCount: bigint,
    poolBalance: bigint
  ];
  export interface OutputObject {
    drawId: bigint;
    ticketCount: bigint;
    poolBalance: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DrawCreatedEvent {
  export type InputTuple = [
    drawId: BigNumberish,
    tier: BigNumberish,
    opensAt: BigNumberish,
    closesAt: BigNumberish,
    ticketPrice: BigNumberish,
    advertisedJackpot: BigNumberish
  ];
  export type OutputTuple = [
    drawId: bigint,
    tier: bigint,
    opensAt: bigint,
    closesAt: bigint,
    ticketPrice: bigint,
    advertisedJackpot: bigint
  ];
  export interface OutputObject {
    drawId: bigint;
    tier: bigint;
    opensAt: bigint;
    closesAt: bigint;
    ticketPrice: bigint;
    advertisedJackpot: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DrawSettledEvent {
  export type InputTuple = [
    drawId: BigNumberish,
    winnerCount: BigNumberish,
    totalPaid: BigNumberish
  ];
  export type OutputTuple = [
    drawId: bigint,
    winnerCount: bigint,
    totalPaid: bigint
  ];
  export interface OutputObject {
    drawId: bigint;
    winnerCount: bigint;
    totalPaid: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PrizeClaimedEvent {
  export type InputTuple = [winner: AddressLike, amount: BigNumberish];
  export type OutputTuple = [winner: string, amount: bigint];
  export interface OutputObject {
    winner: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TicketPurchasedEvent {
  export type InputTuple = [
    ticketId: BigNumberish,
    drawId: BigNumberish,
    buyer: AddressLike,
    numbers: BigNumberish[],
    amountPaid: BigNumberish
  ];
  export type OutputTuple = [
    ticketId: bigint,
    drawId: bigint,
    buyer: string,
    numbers: bigint[],
    amountPaid: bigint
  ];
  export interface OutputObject {
    ticketId: bigint;
    drawId: bigint;
    buyer: string;
    numbers: bigint[];
    amountPaid: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VRFRequestedEvent {
  export type InputTuple = [drawId: BigNumberish, requestId: BigNumberish];
  export type OutputTuple = [drawId: bigint, requestId: bigint];
  export interface OutputObject {
    drawId: bigint;
    requestId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface NeonDrawLottery extends BaseContract {
  connect(runner?: ContractRunner | null): NeonDrawLottery;
  waitForDeployment(): Promise<this>;

  interface: NeonDrawLotteryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  buyTicket: TypedContractMethod<
    [drawId: BigNumberish, numbers: BigNumberish[]],
    [void],
    "payable"
  >;

  claimPrize: TypedContractMethod<[], [void], "nonpayable">;

  closeDraw: TypedContractMethod<[drawId: BigNumberish], [void], "nonpayable">;

  createDraw: TypedContractMethod<
    [
      tier: BigNumberish,
      opensAt: BigNumberish,
      closesAt: BigNumberish,
      ticketPrice: BigNumberish,
      advertisedJackpot: BigNumberish,
      winnerCount: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  draws: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        tier: bigint;
        status: bigint;
        opensAt: bigint;
        closesAt: bigint;
        ticketPrice: bigint;
        advertisedJackpot: bigint;
        poolBalance: bigint;
        ticketCount: bigint;
        winnerCount: bigint;
        vrfRequestId: bigint;
      }
    ],
    "view"
  >;

  fulfillDraw: TypedContractMethod<
    [
      drawId: BigNumberish,
      winningTicketIds: BigNumberish[],
      payoutAmounts: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;

  getDrawTicketIds: TypedContractMethod<
    [drawId: BigNumberish],
    [bigint[]],
    "view"
  >;

  nextDrawId: TypedContractMethod<[], [bigint], "view">;

  nextTicketId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  pendingClaims: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  requestDrawRandomness: TypedContractMethod<
    [drawId: BigNumberish],
    [void],
    "nonpayable"
  >;

  setVRFCoordinator: TypedContractMethod<
    [coordinator: AddressLike],
    [void],
    "nonpayable"
  >;

  tickets: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, boolean] & {
        drawId: bigint;
        owner: string;
        purchasedAt: bigint;
        claimed: boolean;
      }
    ],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  vrfCoordinator: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "buyTicket"
  ): TypedContractMethod<
    [drawId: BigNumberish, numbers: BigNumberish[]],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "claimPrize"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "closeDraw"
  ): TypedContractMethod<[drawId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createDraw"
  ): TypedContractMethod<
    [
      tier: BigNumberish,
      opensAt: BigNumberish,
      closesAt: BigNumberish,
      ticketPrice: BigNumberish,
      advertisedJackpot: BigNumberish,
      winnerCount: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "draws"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        tier: bigint;
        status: bigint;
        opensAt: bigint;
        closesAt: bigint;
        ticketPrice: bigint;
        advertisedJackpot: bigint;
        poolBalance: bigint;
        ticketCount: bigint;
        winnerCount: bigint;
        vrfRequestId: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "fulfillDraw"
  ): TypedContractMethod<
    [
      drawId: BigNumberish,
      winningTicketIds: BigNumberish[],
      payoutAmounts: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getDrawTicketIds"
  ): TypedContractMethod<[drawId: BigNumberish], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "nextDrawId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextTicketId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "pendingClaims"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestDrawRandomness"
  ): TypedContractMethod<[drawId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setVRFCoordinator"
  ): TypedContractMethod<[coordinator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "tickets"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, boolean] & {
        drawId: bigint;
        owner: string;
        purchasedAt: bigint;
        claimed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "vrfCoordinator"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "DrawClosed"
  ): TypedContractEvent<
    DrawClosedEvent.InputTuple,
    DrawClosedEvent.OutputTuple,
    DrawClosedEvent.OutputObject
  >;
  getEvent(
    key: "DrawCreated"
  ): TypedContractEvent<
    DrawCreatedEvent.InputTuple,
    DrawCreatedEvent.OutputTuple,
    DrawCreatedEvent.OutputObject
  >;
  getEvent(
    key: "DrawSettled"
  ): TypedContractEvent<
    DrawSettledEvent.InputTuple,
    DrawSettledEvent.OutputTuple,
    DrawSettledEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PrizeClaimed"
  ): TypedContractEvent<
    PrizeClaimedEvent.InputTuple,
    PrizeClaimedEvent.OutputTuple,
    PrizeClaimedEvent.OutputObject
  >;
  getEvent(
    key: "TicketPurchased"
  ): TypedContractEvent<
    TicketPurchasedEvent.InputTuple,
    TicketPurchasedEvent.OutputTuple,
    TicketPurchasedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "VRFRequested"
  ): TypedContractEvent<
    VRFRequestedEvent.InputTuple,
    VRFRequestedEvent.OutputTuple,
    VRFRequestedEvent.OutputObject
  >;

  filters: {
    "DrawClosed(uint256,uint256,uint256)": TypedContractEvent<
      DrawClosedEvent.InputTuple,
      DrawClosedEvent.OutputTuple,
      DrawClosedEvent.OutputObject
    >;
    DrawClosed: TypedContractEvent<
      DrawClosedEvent.InputTuple,
      DrawClosedEvent.OutputTuple,
      DrawClosedEvent.OutputObject
    >;

    "DrawCreated(uint256,uint8,uint64,uint64,uint256,uint256)": TypedContractEvent<
      DrawCreatedEvent.InputTuple,
      DrawCreatedEvent.OutputTuple,
      DrawCreatedEvent.OutputObject
    >;
    DrawCreated: TypedContractEvent<
      DrawCreatedEvent.InputTuple,
      DrawCreatedEvent.OutputTuple,
      DrawCreatedEvent.OutputObject
    >;

    "DrawSettled(uint256,uint256,uint256)": TypedContractEvent<
      DrawSettledEvent.InputTuple,
      DrawSettledEvent.OutputTuple,
      DrawSettledEvent.OutputObject
    >;
    DrawSettled: TypedContractEvent<
      DrawSettledEvent.InputTuple,
      DrawSettledEvent.OutputTuple,
      DrawSettledEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PrizeClaimed(address,uint256)": TypedContractEvent<
      PrizeClaimedEvent.InputTuple,
      PrizeClaimedEvent.OutputTuple,
      PrizeClaimedEvent.OutputObject
    >;
    PrizeClaimed: TypedContractEvent<
      PrizeClaimedEvent.InputTuple,
      PrizeClaimedEvent.OutputTuple,
      PrizeClaimedEvent.OutputObject
    >;

    "TicketPurchased(uint256,uint256,address,uint8[6],uint256)": TypedContractEvent<
      TicketPurchasedEvent.InputTuple,
      TicketPurchasedEvent.OutputTuple,
      TicketPurchasedEvent.OutputObject
    >;
    TicketPurchased: TypedContractEvent<
      TicketPurchasedEvent.InputTuple,
      TicketPurchasedEvent.OutputTuple,
      TicketPurchasedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "VRFRequested(uint256,uint256)": TypedContractEvent<
      VRFRequestedEvent.InputTuple,
      VRFRequestedEvent.OutputTuple,
      VRFRequestedEvent.OutputObject
    >;
    VRFRequested: TypedContractEvent<
      VRFRequestedEvent.InputTuple,
      VRFRequestedEvent.OutputTuple,
      VRFRequestedEvent.OutputObject
    >;
  };
}
