/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as neonDrawLotterySol from "./NeonDrawLottery.sol";
export type { neonDrawLotterySol };
import type * as mocks from "./mocks";
export type { mocks };
