/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IJackpotVRF,
  IJackpotVRFInterface,
} from "../../../contracts/NeonDrawLottery.sol/IJackpotVRF";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "drawId",
        type: "uint256",
      },
    ],
    name: "requestRandomWords",
    outputs: [
      {
        internalType: "uint256",
        name: "requestId",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IJackpotVRF__factory {
  static readonly abi = _abi;
  static createInterface(): IJackpotVRFInterface {
    return new Interface(_abi) as IJackpotVRFInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IJackpotVRF {
    return new Contract(address, _abi, runner) as unknown as IJackpotVRF;
  }
}
