/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  MockJackpotVRF,
  MockJackpotVRFInterface,
} from "../../../contracts/mocks/MockJackpotVRF";

const _abi = [
  {
    inputs: [],
    name: "nextRequestId",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "requestRandomWords",
    outputs: [
      {
        internalType: "uint256",
        name: "requestId",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052600160005534801561001557600080fd5b5060e7806100246000396000f3fe6080604052348015600f57600080fd5b506004361060325760003560e01c80636a84a985146037578063bc85777c146051575b600080fd5b603f60005481565b60405190815260200160405180910390f35b603f605c3660046073565b600080548180606983608b565b9091555092915050565b600060208284031215608457600080fd5b5035919050565b60006001820160aa57634e487b7160e01b600052601160045260246000fd5b506001019056fea2646970667358221220fb9b6677402b881cd0b33a8c0a71ce17ac57524600c97da15c9254e502e5be5a64736f6c63430008180033";

type MockJackpotVRFConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockJackpotVRFConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockJackpotVRF__factory extends ContractFactory {
  constructor(...args: MockJackpotVRFConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MockJackpotVRF & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MockJackpotVRF__factory {
    return super.connect(runner) as MockJackpotVRF__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockJackpotVRFInterface {
    return new Interface(_abi) as MockJackpotVRFInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MockJackpotVRF {
    return new Contract(address, _abi, runner) as unknown as MockJackpotVRF;
  }
}
